dist: bionic
sudo: required
language: cpp

addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-all-dev

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_script:
  - git lfs pull
  - git submodule init
  - git submodule update
  - bash download_models.sh
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - make test
  - cd ..
  - bash test_canonical.sh
