dist: bionic
sudo: required
language: cpp

addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-all-dev

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - git lfs pull
  - git submodule init
  - git submodule update

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make
    - make test
    - cd ..
